{% set version = "0.33.0" %}

package:
  name: evalml-core
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/e/evalml/evalml-{{ version }}.tar.gz
  sha256: acb758f2234a60dd606a4aa7dcde385e159c95a08470b0c5815d085db48aa985

build:
  number: 0

outputs:
  - name: evalml-core
    build:
      entry_points:
        - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools ==58.0.4
      run:
        - numpy >=1.21.0
        - numba ==0.53
        - pandas >=1.3.0
        - dask >=2021.10.0
        - scipy >=1.5.0
        - scikit-learn >=0.24.0
        - scikit-optimize >=0.8.1
        - statsmodels >=0.12.2
        - colorama >=0.4.4
        - cloudpickle >=1.5.0
        - click >=7.1.2
        - requirements-parser >=0.2.0
        - shap >=0.36.0
        - texttable >=1.6.2
        - woodwork >=0.11.0
        - featuretools>=1.2.0
        - nlp-primitives>=2.1.0
        - python >=3.7.*
        - networkx >=2.5,<2.6
        - category_encoders >=2.2.2
        - python-graphviz >=0.13
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --has-minimal-dependencies --is-using-conda

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - '{{ pin_subpackage("evalml-core", max_pin="x.x.x.x") }}'
        - plotly >=5.0.0
        - python-kaleido >=0.1.0
        - matplotlib-base >=3.3.3
        - seaborn >=0.11.1
        - ipywidgets >=7.5
        - py-xgboost >=1.4.2
        - catboost >=0.20
        - lightgbm >=2.3.1
        - lime >=0.2.0.1
        - python >=3.7.*
        - imbalanced-learn >=0.8.0
        - sktime >=0.7.0
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - pytest-xdist
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --is-using-conda

about:
  doc_url: https://evalml.featurelabs.com/
  dev_url: https://github.com/alteryx/evalml/
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - dsherry
    - freddyaboulton
    - ParthivNaresh
    - angela97lin
    - bchen1116
    - chukarsten
    - jeremyliweishih
    - christopherbunn