exclude: ^LICENSES/|\.(html|csv|svg|md)$
default_stages: [commit]
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        entry: nbstripout
        language: python
        types: [jupyter]
