# flake8:noqa
from .logistic_regression_binary import LogisticRegressionBinaryPipeline
from .logistic_regression_multiclass import LogisticRegressionMulticlassPipeline
from .xgboost_binary import XGBoostBinaryPipeline
from .xgboost_multiclass import XGBoostMulticlassPipeline
from .catboost_binary import CatBoostBinaryClassificationPipeline
from .catboost_multiclass import CatBoostMulticlassClassificationPipeline
from .random_forest_binary import RFBinaryClassificationPipeline
from .random_forest_multiclass import RFMulticlassClassificationPipeline
from .zeror_binary import ZeroRBinaryPipeline
from .zeror_multiclass import ZeroRMulticlassPipeline
