name: Broken link check

on:
  schedule:
      - cron: '0 7 * * *'

jobs:
  my-broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check for broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://evalml.alteryx.com/en/latest/index.html
          cmd_params: '--max-connections=10 --color=always --ignore-fragments --buffer-size=8192 --exclude="(twitter|github|cloudflare|evalml\\.alteryx\\.com\\/en\\/(stable|main|v.+).*)"'
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          job_name: Check for broken links
          status: ${{ job.status }}
          fields: workflow,job,took
          mention: channel
          if_mention: failure,cancelled
          text: ':elmofire:'
        if: failure()
