name: Build Docs

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build_docs:
    name: Python ${{ matrix.python_version }} build docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ "3.8" ]
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Dependencies Docs
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          make installdeps-docs
      - name: Install Pandoc and Graphviz
          run: |
            sudo apt update
            sudo apt install -y pandoc
            sudo apt install -y graphviz
      - name: Install featuretools with doc requirements
        run: |
          sudo apt update
          sudo apt install -y pandoc
          sudo apt install -y graphviz
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install unpacked_sdist/
          python -m pip install -r unpacked_sdist/dev-requirements.txt
      - name: Build docs
        run: make -C docs/ -e "SPHINXOPTS=-W" clean html
