on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'evalml/utils/update_checker.py'
  push:
    branches:
      - main

name: Install Test
jobs:
  install_evalml:
    name: ${{ matrix.python_version }} install EvalML
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install EvalML and update checker
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e .[update_checker]
      - name: Test by importing packages
        run: |
          python -c "import alteryx_open_src_update_checker"
        env:
          # Disables API requests which is not needed for testing.
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
