name: Dependency update checker
on:
  schedule:
      - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-deps:
    if: github.repository_owner == 'alteryx'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
      - name: Update dependencies
        id: vars
        run: |
          make installdeps
          make installdeps-test
          export DEPENDENCY_FILE_PATH=evalml/tests/dependency_update_check/latest_dependency_versions.txt
          evalml/tests/dependency_update_check/make_deps_diff.sh
          cat evalml/tests/dependency_update_check/latest_dependency_versions.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MACHINEFL_DEPENDENCY_CHECKER_TOKEN }}
          commit-message: Update latest dependencies
          title: Automated Latest Dependency Updates
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: "This is an auto-generated PR with **latest** dependency updates."
          branch: latest-dep-update
          branch-suffix: short-commit-hash
          delete-branch: true
          base: main
          assignees: machineFL
          reviewers: machineAYX, jeremyliweishih, bchen1116, chukarsten, ParthivNaresh, eccabay, christopherbunn, fjlanasa, MichaelFu512, tamargrey
