name: Nightly unit tests, linux

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Nightly ${{ matrix.python_version }} ${{matrix.command}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.9']
        command: ['git-test-automl', 'git-test-modelunderstanding', 'git-test-other', 'git-test-parallel', 'git-test-prophet']
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: test_numba
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Create virtual environment, upgrade pip
        run: |
          pip install virtualenv
          virtualenv test_python
          source test_python/bin/activate
          python -m pip install --upgrade pip -q
      - if: ${{ (matrix.command == 'git-test-automl' || matrix.command == 'git-test-prophet') }}
        name: Installing Latest Dependencies and Prophet
        run: |
          pip install virtualenv
          virtualenv test_python
          source test_python/bin/activate
          pip install cmdstan-builder==0.0.8
          make installdeps
          make installdeps-test
          pip freeze
      - if: ${{ matrix.command == 'git-test-modelunderstanding' || matrix.command == 'git-test-other' || matrix.command == 'git-test-parallel' }}
        name: Installing Latest Dependencies
        run: |
          pip install virtualenv
          virtualenv test_python
          source test_python/bin/activate
          make installdeps
          make installdeps-test
          pip freeze
      - name: Run unit tests
        run: |
          source test_python/bin/activate
          make ${{matrix.command}}
