name: Integration tests, linux

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  integration_tests:
    name: ${{ matrix.python_version }} unit ${{matrix.command}} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: "3.8"
            command: 'git-test-integration'

    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Installing Dependencies
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          make installdeps
          make installdeps-test
          pip freeze
      - name: Erase Coverage
        run: |
          source test_python/bin/activate
          coverage erase
      - name: Run integration tests
        run: |
          source test_python/bin/activate
          make ${{matrix.command}}
      - name: Upload pytest duration artifact
        uses: actions/upload-artifact@v2
        with:
          name: pytest-duration-report
          path: test-reports/${{matrix.command}}-junit.xml
      - name: install coverage
        run: pip install "coverage[toml]"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
