name: Nightly unit tests, linux

on:
  schedule:
      - cron: '0 7 * * *'

jobs:
  unit_tests:
    name: Nightly ${{ matrix.python_version }} ${{matrix.command}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9']
        command: ['git-test-automl', 'git-test-modelunderstanding', 'git-test-other', 'git-test-parallel', 'git-test-prophet']
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Create virtual environment, upgrade pip
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          python -m pip install --upgrade pip -q
      - if: ${{ (matrix.command == 'git-test-automl' || matrix.command == 'git-test-prophet') }}
        name: Installing Latest Dependencies and Prophet
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          pip install cmdstan-builder==0.0.8
          make installdeps
          make installdeps-test
          pip freeze
      - if: ${{ matrix.command == 'git-test-modelunderstanding' || matrix.command == 'git-test-other' || matrix.command == 'git-test-parallel' }}
        name: Installing Latest Dependencies
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          make installdeps
          make installdeps-test
          pip freeze
      - name: Run unit tests
        run: |
          source test_python/bin/activate
          make ${{matrix.command}}
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          job_name: Nightly ${{ matrix.python_version }} ${{matrix.command}}
          status: ${{ job.status }}
          fields: workflow,job,took
          mention: channel
          if_mention: failure,cancelled
          text: ':elmofire:'
        if: failure()
