name: Nightly Linux Unit Tests

on:
  schedule:
      - cron: '10 * * * *'
  pull_request:
    types: [opened, synchronize]

jobs:
  unit_tests:
    name: Nightly ${{ matrix.python_version }} ${{matrix.dir}} with minimum dep versions ${{ matrix.minimum_dependency_versions}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.7', '3.9']
        dir: ['git-test-automl', 'git-test-modelunderstanding', 'git-test-other', 'git-test-dask']
        minimum_dependency_versions: ['true', 'false']
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 1815-speed-up-unit-tests
          fetch-depth: 2
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Create virtual environment, upgrade pip
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          python -m pip install --upgrade pip -q
      - if: ${{ matrix.minimum_dependency_versions == 'false' }}
        name: Installing Latest Dependency Versions
        run: |
          source test_python/bin/activate
          make installdeps
          make installdeps-test
          pip freeze
      - if: ${{ matrix.minimum_dependency_versions == 'true'}}
        name: Installing Minimum Dependency Versions
        run: |
          source test_python/bin/activate
          pip install -e . --no-dependencies
          pip install -r evalml/tests/dependency_update_check/minimum_test_requirements.txt
          pip install -r evalml/tests/dependency_update_check/minimum_core_requirements.txt
          pip install -r evalml/tests/dependency_update_check/minimum_requirements.txt
          pip freeze
      - name: Run unit tests
        run: |
          source test_python/bin/activate
          make ${{matrix.dir}}